Android cheat sheet
------------------
Databinding
~~~~~~~~~~~
* Binding class:
+
[source,java]
-----------------
super.onCreate(savedInstanceState);

ctivityMainBinding binding = DataBindingUtil.setContentView(this, R.layout.activity_main);
QuizMaster qm = QuizMaster.getInstance();
binding.setQuestion(qm.getCurrentQuestion());
-----------------

* Expression language:
+
[source,java]
-----------------
android:text="@{String.valueOf(index + 1)}"
android:visibility="@{age > 13 ? View.GONE : View.VISIBLE}"

-----------------
* Events:
+
[source,java]
-----------------
public void onClickFriend(View view) { ... }
android:onClick="@{handlers::onClickFriend}"

-----------------
* Two-way data binding:
+
[source,java]
-----------------
android:text="@={Converter.dateToString(viewmodel.birthDate)}"
-----------------

ViewModel
~~~~~~~~~
* Get Viewmodel
+
[source,java]
-----------------
QuoteAppViewModel model = ViewModelProviders.of(this).get(QuoteAppViewModel.class);
b.setLifecycleOwner(this);

//New version
ViewModelProvider.Factory factory = ViewModelProvider.AndroidViewModelFactory.getInstance(getApplication());
ViewModelProvider viewModelProvider = new ViewModelProvider(this, factory);
MainViewModel vm = viewModelProvider.get(MainViewModel.class);
b.setLifecycleOwner(this)
-----------------
* Viewmodel class
+
[source,java]
-----------------
public class QuoteAppViewModel extends AndroidViewModel {
     public QuoteAppViewModel(@NonNull Application application) {
        super(application);
    }
}

-----------------

Room
~~~~
* Dao
+
[source,java]
-----------------
@Dao
public interface TrafficDao {

    @Insert
    void insertAll(TrafficNotification... trafficNotifications);
    @Query("DELETE from trafficnotification")
    void deleteALl();
    @Query("SELECT * FROM trafficnotification")
    List<TrafficNotification> getAll();
    @Delete
    void delete(TrafficNotification trafficNotification);

}
-----------------
* PoCo
+
[source,java]
-----------------
@Entity
public class TrafficNotification {
    @PrimaryKey
    @NonNull
    private String id;
    private String name;

    @Ignore
    public TrafficNotification(String name) {
        this(UUID.randomUUID().toString(), name);
    }

    public TrafficNotification(String id, String name) {
        this.id = id;
        this.name = name;
    }
}
-----------------
* AppDatabase
+
[source,java]
-----------------
@Database(entities = {TrafficNotification.class}, version = 1)
public abstract class TrafficNotificationDataBase extends RoomDatabase {
    private static final TrafficNotificationDataBase db = null;
    public abstract TrafficDao trafficDao();

    static TrafficNotificationDataBase getDatabase(Context context){
        if(db == null){
            TrafficNotificationDataBase db = Room.databaseBuilder(context, TrafficNotificationDataBase.class, "trafficNotification").allowMainThreadQueries().build();
            return db;
        }else{
            return db;
        }
    }
}
-----------------
* ViewModel
+
[source,java]
-----------------
	AppDatabase db = AppDatabase.getDatabase(application);
    TrafficNotificationDao dao = db.trafficNotificationDao();
    dao.deleteALl();
    try{
        JSONObject json = JsonUtils.loadJSONFromAsset(application, "verkeersmeldingen.json");
        List<TrafficNotification> notifications = JsonUtils.parseJSON(json);
        dao.insertAll(notifications.toArray(new TrafficNotification[0]));
    }catch(IOException e) {e.printStackTrace();
    }catch(JSONException e) {e.printStackTrace();
        }
    List<TrafficNotification> allTrafficNotifications = dao.getAll();
-----------------

Navigation
~~~~~~~~~~
* Navigate
+
[source,java]
-----------------
public void ClickNavigate(View view){
	Navigation.findNavController(view).navigate(R.id.action_mainFragment_to_detailFragment2);
}
-----------------
* onCreateView
+
[source,java]
-----------------
FragmentMainBinding binding = DataBindingUtil.inflate(inflater, R.layout.fragment_main, container, false);
View v = binding.getRoot();
return v;
-----------------
